[general]
import = [
"~/alacritty/themes/themes/github_light.toml"
]

[env]
TERM = "xterm-256color"
EDITOR = "emacs"

[window]
dimensions = { columns = 100, lines  = 50 }
padding = { x = 10, y  = 10 }
decorations_theme_variant = "Dark"
decorations = "Transparent"
option_as_alt = "Both"

[scrolling]
history = 10000
multiplier = 3

[font]
normal = { family = "Monolisa Variable", style = "SemiBold" }
size = 14

[selection]
save_to_clipboard = true
